repos:
    - repo: local
      hooks:
        - id: black
          name: black
          entry: if black
          language: system
          files: r"*.py"
        - id: flake8
          name: flake8
          entry: flake8
          language: system
          files: r"*.py"
