repos:
    - repo: local
      hooks:
        - id: black
          name: black
          entry: black
          language: python
          files: ".py"
        - id: flake8
          name: flake8
          entry: flake8
          language: python
          files: ".py"
