name: CI

on:
  push:
    branches:
      - main
    tags: '*'

  pull_request:
    branches:
      - main

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    name: Python ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        arch: [x64, x86]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

        exclude:
          - os: macOS-latest
            arch: x86

    runs-on: ${{ matrix.os }}

    env:
        codecov-arch: x64
        codecov-version: '1.7'

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python {{ matrix.python-version }} - ${{ matrix.os }} - ${{ matrix.arch }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install flake8 pytest
#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

#      - name: Lint with flake8
#        run: |
#          # stop the build if there are Python syntax errors or undefined names
#          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

#      - name: Test with pytest
#        run: |
#          pytest

      - name: Install tox
        run: pip install tox

      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
